---
job_templates:
  - name: "CaC"
    organization: "Default"
    inventory: "Demo Inventory"
    project: "GitLab"
    playbook: "CaC/playbooks/deploy_main.yaml"
    execution_environment: "ee-supported-rhel9"
    credentials:
      - "ansible controller creds for CaC"
      - "Ansible-Vault decryption for CaC GitOps"
    job_type: "run"
    verbositry: 0
    ask_variables_on_launch: false

  - name: "openshit-example-template"
    organization: "Default"
    labels:
    - "openshift"
    inventory: "Demo Inventory"
    project: "GitLab"
    playbook: "playbooks/some_ocp_automation.yaml"
    execution_environment: "custom-ocp_EE" #NEW
    credentials:
      - "GitLab credential"
      - "openshift-token"
      - "vault token" #if vault
    job_type: "run"
    verbositry: 0
    extra_vars:
      env: null
      namespace: null
    ask_variables_on_launch: false